__author__ = "Aleksei Tsysin"
__copyright__ = "Copyright 2021, ISG Neuro"
__credits__ = []
__license__ = ""
__version__ = "0.1.0"
__api_version__ = "1"
__maintainer__ = "Aleksei Tsysin"
__email__ = "atsysin@isgneuro.com"
__status__ = "Dev"
