__author__ = "Aleksei Tsysin"
__copyright__ = "Copyright 2024, ISG Neuro"
__credits__ = []
__license__ = ""
__version__ = "0.4.0"
__api_version__ = "2"
__maintainer__ = "Nikita Serditov"
__email__ = "nserditov@isgneuro.com"
__status__ = "Dev"
